version: '3.8'
services:
    db:
        image: mysql:8.0
        container_name: lamp_db
        restart: unless-stopped
        env_file: .env
        environment:
          MYSQL_DATABASE: exampledb
          MYSQL_USER: exampleuser
          MYSQL_PASSWORD: examplepass
          MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
          - db:/var/lib/mysql
    wordpress:
        depends_on:
            - db
        image: wordpress
        container_name: lamp_wordpress
        restart: unless-stopped
        ports:
            - 80:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        volumes:
        - wordpress:/var/www/html
volumes:
  wordpress:
  db: