version: '3.7'

services:
# php:
#   build: './php'
#   restart: always
#   links:
#     - db
#   networks: 
#     - backend
#   volumes:
#     - wordpress:/var/www/html
#     - ./public_html:/usr/local/apache2/htdocs
#     - ./tmp:/usr/local/tmp
  db:
    build: './mysql'
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - backend
    volumes:
      - dbdata:/var/lib/mysql
# apache:
#   depends_on:
#     - wordpress
#     - php
#     - db
#   build: './apache'
#   restart: always
#   links: 
#     - db
#   ports:
#     - 80:80
#     - 443:443
#   networks: 
#     - frontend
#     - backend
#   volumes:
#     - wordpress:/var/www/html
#     #- ./public_html:/usr/local/apache2/htdocs
#     #- ./apache/cert/:/usr/local/apache2/cert/
  wordpress:
    depends_on:
      - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - backend

volumes:
  #ertbot-etc:
  wordpress:
  dbdata:
  apache:

networks: 
  backend:
  frontend:

